### ISSUE TITLE
Validate access token for a resource server

### ISSUE THREAD

**Issue by thoangtd** [kangaroo-server/kangaroo#441]
In Grant Type: client_credentials
 Client get access token from Authentication server, client add to header  "Authorization" this access token to access resource . how does resource server validate access token with Authentication server.

https://stackoverflow.com/questions/12296017/how-to-validate-an-oauth-2-0-access-token-for-a-resource-server

**Comment by krotscheck** [comment]
The short answer is: Use the Token introspection endpoint as per RFC7662, exposed at `/introspect`.

Our implementation permits two different ways for the resource server to structure the request. The difference is if the resource server is registered as a client_credentials client, or if they are simply a passthrough for the original client's token.

**Case 1: The resource server is, itself, a client for the same application.**
(In this case, basic auth is the client_id and client_secret of the resource server).
```
POST /introspect
authorization: Basic MTIxNzEzZjcyYmMxMGEwMmMwYjUwNzE1MGY5MGYzODE6NGU1YTcyMTEzOTYzNmUyMmEwZjllMzFiNzU4ZGJkOTc=
content-type: application/x-www-form-urlencoded

token=38ad8c93028c2e4a2706e0a6aa71b5bb
```

**Case 2: The resource server is only a passthrough.**
(In this case, you can use the bearer token itself to validate itself)
```
POST /introspect
authorization: Bearer 38ad8c93028c2e4a2706e0a6aa71b5bb
x-requested-with: Kangaroo Test Harness
content-type: application/x-www-form-urlencoded

token=38ad8c93028c2e4a2706e0a6aa71b5bb
```

The expected response on success looks like this.
```
HTTP 200 OK
content-type: application/json

{"active":true,"scope":"debug","username":"260ecc54f88ddb30a028e607203ca967","exp":1519878246,"iat":1519878146,"nbf":1519878146,"sub":"6ceeeff94d534f69bde1f28e1923c153","aud":"4aa0986b01638495b65768c4721ddcbd","iss":"localhost","jti":"38ad8c93028c2e4a2706e0a6aa71b5bb","client_id":"121713f72bc10a02c0b507150f90f381","token_type":"Bearer"}
```

The response for a failure looks like this:
```
HTTP 200 OK

{"active":false}
```

I'll make a note to add this to the documentation.

**Comment by krotscheck** [comment]
Hrm. The more I think about this, the more I think you've found a bug. The introspection endpoint right now presumes that you're either a client credentials client, OR you're a a bearer token associated with a user. The passthrough case I mentioned above isn't actually supported if you're using a token received from a third client-credentials client.

Now, frankly, I'm not certain why you'd be willing to pass a client credentials based token through another resource server, however the passthrough case should still be supported. I'll note a bug.

**Comment by thoangtd** [comment]
it's work !
Thanks for support,

`sub = 71e43c6bea8532b3ccfafea7b4e533c1
  aud = 56565e8dec6da31fbc7cc7ef08d0cca7
  nbf = 1519886410
  scope = 
  iss = localhost
  active = true
  exp = 1519887010
  token_type = Bearer
  iat = 1519886410
  jti = 67beb56c4f91e8fcddd995d53f950e45
  client_id = 71e43c6bea8532b3ccfafea7b4e533c1
{"sub":"71e43c6bea8532b3ccfafea7b4e533c1","aud":"56565e8dec6da31fbc7cc7ef08d0cca7","nbf":1519886410,"scope":"","iss":"localhost","active":true,"exp":1519887010,"token_type":"Bearer","iat":1519886410,"jti":"67beb56c4f91e8fcddd995d53f950e45","client_id":"71e43c6bea8532b3ccfafea7b4e533c1"}
`

**Comment by krotscheck** [comment]
No problem! Anytime :).

You did find a bug though, so I'll be leaving this ticket open until I fix it :)
